---
deployment:
  tasks:
    - export DEPLOYPATH=/home/panel/public_html
    - /bin/cp $DEPLOYPATH/.env $HOME/env_backup 2>/dev/null || true
    - /bin/cp $DEPLOYPATH/.htaccess $HOME/htaccess_backup 2>/dev/null || true
    - cd $DEPLOYPATH
    - /bin/cp $HOME/env_backup $DEPLOYPATH/.env 2>/dev/null || true
    - /bin/cp $HOME/htaccess_backup $DEPLOYPATH/.htaccess 2>/dev/null || true
    - /usr/local/bin/php /usr/local/bin/composer install --no-dev --optimize-autoloader --no-interaction
    - /usr/local/bin/php artisan migrate --force
    - /usr/local/bin/php artisan config:cache
    - /usr/local/bin/php artisan route:cache
    - /usr/local/bin/php artisan view:cache
    - /usr/local/bin/php artisan storage:link 2>/dev/null || true
    - chmod -R 755 storage bootstrap/cache
