<?php

namespace Modules\Technician\Models;

use Illuminate\Database\Eloquent\Model;

class TechnicianRegistration extends Model
{
    protected $table = 'technician_registrations';

    protected $fillable = [
        'mobile',
        'national_code',
        'national_card_serial',
        'birth_date',
        'first_name',
        'last_name',
        'father_name',
        'mobile_verified_at',
        'identity_verified',
        'biometric_status',
        'biometric_session_id',
        'biometric_media_id',
        'biometric_video_path',
        'biometric_reject_reason',
        'biometric_verified_at',
        'shenasname_number',
        'gender',
        'marital_status',
        'children_count',
        'province',
        'city',
        'field_of_study',
        'education_level',
        'has_business_license',
        'has_shop',
        'shop_address',
        'shop_phone',
        'has_cooperation',
        'cooperation_companies',
        'referrer_name',
        'referrer_phone',
        'colleague1_name',
        'colleague1_phone',
        'colleague2_name',
        'colleague2_phone',
        'work_experiences',
        'certificates',
        'tehran_districts',
        'tehran_province_cities',
        'alborz_cities',
        'other_provinces_cities',
        'activity_type',
        'appliance_categories',
        'transportation_method',
        'repair_skill',
        'board_repair_experience',
        'additional_notes',
        'current_step',
        'status',
        'rejection_reason',
        'archived_at',
        'archive_reason',
        'admin_notes',
        'contract_signed_at',
        'contract_signature',
        'contract_number',
        'commission_percent',
        'promissory_note_amount',
        'doc_national_card_front',
        'doc_national_card_back',
        'doc_birth_certificate_p1',
        'doc_birth_certificate_p2',
        'doc_criminal_record',
        'doc_photo_3x4',
        'doc_lease_agreement',
        'doc_utility_bill',
        'documents_uploaded',
        'documents_reject_reason',
        'contract_reject_reason',
        'promissory_note_path',
        'promissory_note_uploaded_at',
        'promissory_note_status',
        'promissory_note_reject_reason',
    ];

    protected $casts = [
        'mobile_verified_at' => 'datetime',
        'contract_signed_at' => 'datetime',
        'biometric_verified_at' => 'datetime',
        'promissory_note_uploaded_at' => 'datetime',
        'archived_at' => 'datetime',
        'identity_verified' => 'boolean',
        'has_business_license' => 'boolean',
        'has_shop' => 'boolean',
        'has_cooperation' => 'boolean',
        'work_experiences' => 'array',
        'certificates' => 'array',
        'tehran_districts' => 'array',
        'tehran_province_cities' => 'array',
        'alborz_cities' => 'array',
        'appliance_categories' => 'array',
        'documents_uploaded' => 'boolean',
    ];
}
